### ISSUE TITLE
have error with SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by zhangyaocheng** [pubkey/eth-crypto#18] opened 2019-01-19 03:37 UTC
I have a error with using this tool.

I am working in VSCode, and get eth-crypto with npm. 
This is my code:
```
var ecrypt = require("eth-crypto")

var publickey = ecrypt.publicKeyByPrivateKey("0x5be62b0a12749df7d52cefb5c95219eff490cd4a6c2084a55a6571a828b9455a")
console.log("public:"+publickey)

var address = ecrypt.publicKey.toAddress(publickey)
console.log("address:"+address)

// test for encrypting data with eth-crypto
var cipher = await ecrypt.encryptWithPublicKey(publickey,"This is a game by zyc");
console.log("cipher:"+cipher);
var decrypt = await ecrypt.decryptWithPrivateKey("0x5be62b0a12749df7d52cefb5c95219eff490cd4a6c2084a55a6571a828b9455a",cipher)
console.log("decrypt"+decrypt)

```

And when run in cmd enviroment, it will show the following errors:
```
var cipher = await ecrypt.encryptWithPublicKey(publickey,"This is a game by zyc");
                              ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
it may be say that ecrypt is not expected indentifier, but i don't know to repairt that. 
I have try to use `Encrypt` to replace `encrypt`, but it don't work

**Comment by zhangyaocheng** [comment] 2019-01-20 10:59
yeah, I have resolved this work in react.
And this is my code in utils.js
```
import ethcrypt from "eth-crypto"



    const publickeyToAddress = (publickey) =>
        new Promise((resolve,reject)=>{
            try {
                const address = ethcrypt.publicKey.toAddress(publickey)
                console.log(address)
                resolve(address)
            }catch (error){
                reject(error)
            }
            
            
    })

    const encryptWithPublickeyToText = (publickey,text) => 
        new Promise((resolve,reject)=>{
            const cipher = ethcrypt.encryptWithPublicKey(publickey,text) 
            const promisereuslt = cipher.then((v)=>{
                var cipherjson = {
                    ciphertext:v.ciphertext,
                    ephemPublicKey:v.ephemPublicKey,
                    iv:v.iv,
                    mac:v.mac
                }
                
                const ciphercontent = ethcrypt.cipher.stringify(cipherjson)
                resolve(ciphercontent)
            
            }).catch((v)=>{
                reject(v)
              
            })
        })
const decryptwithprivatekeyfromcipher = (privatekey,cipher) => 
        new Promise((resovle,reject)=>{
            const cipherdata = ethcrypt.cipher.parse(cipher)
            const data = ethcrypt.decryptWithPrivateKey(privatekey,cipherdata)
            const promiseresult = data.then((v)=>{
                const result = v 
                resovle(result)
            }).catch((v)=>{
                reject(v)
            })
        })

export {publickeyToAddress,encryptWithPublickeyToText,decryptwithprivatekeyfromcipher}
```
you can use those code like following:
```
import React,{Component} from "react"
import {publickeyToAddress,encryptWithPublickeyToText,decryptwithprivatekeyfromcipher} from './utils'

class App8 extends React.Component {
    constructor(props){
        super(props)
        this.state = {data:this.props.data,publickey:this.props.publickey,privatekey:this.props.privatekey,cipher:'',decryptdata:'',addr:''}
        this.transpubtoadd = this.transpubtoadd.bind(this)
        this.encrywithpublictotext = this.encrywithpublictotext.bind(this)
        this.decryptwithprivatekeyfromCipher = this.decryptwithprivatekeyfromCipher.bind(this)
    }

    transpubtoadd = async() =>{
        // console.log(this.state.data)
        // console.log(publickeyToAddress(this.state.data))
        const result = await publickeyToAddress(this.state.publickey)
        this.setState({
            addr: result
        })
        // console.log(result)
        // this.setState({
        //     addr: publickeyToAddress(this.state.publickey)
        // })
    }

    decryptwithprivatekeyfromCipher = async () =>{
        const result = await decryptwithprivatekeyfromcipher(this.state.privatekey,this.state.cipher)
        this.setState({
            decryptdata: result
        })
    }

    encrywithpublictotext = async () =>{

        const result = await encryptWithPublickeyToText(this.state.publickey,this.state.data)
        console.log("cipher zyc:"+result)
        this.setState({
            cipher : result
        })
    }
    render(){
        return ();
 }
}
export default App8; // this just used to show in browse. 
```

This library is truly a good tool for me. But i still have some other questions. 
It is that my ciphertext is different in every time i encrypt data with using encrypt command. What can i do to make that ciphertext be same at every time i encrypt it? Or, it can be done?

**Comment by pubkey** [comment] 2019-01-20 13:43
The encyption is using an ephemeral key which is generated random. https://en.wikipedia.org/wiki/Ephemeral_key

I'm closing this since the issue is solved.

**Closed by pubkey** 2019-01-20 13:43 UTC

**Comment by zhangyaocheng** [comment] 2019-01-20 13:44
Ok, i find it. i have fork the code to change it .



910486122@qq.com
 
From: pubkey
Date: 2019-01-20 21:43
To: pubkey/eth-crypto
CC: zhangyaocheng; Author
Subject: Re: [pubkey/eth-crypto] have error with SyntaxError: Unexpected identifier (#18)
The encyption is using an ephemeral key which is generated random. https://en.wikipedia.org/wiki/Ephemeral_key
I'm closing this since the issue is solved.
